#if !defined(AFX_COCSCN_H__207C7C25_2AC4_45E7_AE86_21DA0A0D9CBB__INCLUDED_)
#define AFX_COCSCN_H__207C7C25_2AC4_45E7_AE86_21DA0A0D9CBB__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCoCSn wrapper class

class CCoCSn : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCoCSn)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xccb90232, 0xb81e, 0x11d2, { 0xab, 0x74, 0x0, 0x40, 0x5, 0x4c, 0x37, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetOpenResult();
	BOOL GetAutoDisable();
	void SetAutoDisable(BOOL bNewValue);
	long GetBinaryConversion();
	void SetBinaryConversion(long nNewValue);
	long GetCapPowerReporting();
	CString GetCheckHealthText();
	BOOL GetClaimed();
	long GetDataCount();
	BOOL GetDataEventEnabled();
	void SetDataEventEnabled(BOOL bNewValue);
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL bNewValue);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL bNewValue);
	long GetPowerNotify();
	void SetPowerNotify(long nNewValue);
	long GetPowerState();
	long GetResultCode();
	long GetResultCodeExtended();
	long GetState();
	CString GetControlObjectDescription();
	long GetControlObjectVersion();
	CString GetServiceObjectDescription();
	long GetServiceObjectVersion();
	CString GetDeviceDescription();
	CString GetDeviceName();
	long CheckHealth(long Level);
	long ClaimDevice(long Timeout);
	long ClearInput();
	long Close();
	long DirectIO(long Command, long* pData, BSTR* pString);
	long Open(LPCTSTR DeviceName);
	long ReleaseDevice();
	BOOL GetCapAutoGenerateFileID();
	BOOL GetCapAutoGenerateImageTagData();
	BOOL GetCapAutoSize();
	long GetCapColor();
	BOOL GetCapConcurrentMICR();
	BOOL GetCapDefineCropArea();
	long GetCapImageFormat();
	BOOL GetCapImageTagData();
	BOOL GetCapMICRDevice();
	BOOL GetCapStoreImageFiles();
	BOOL GetCapValidationDevice();
	long GetColor();
	void SetColor(long nNewValue);
	BOOL GetConcurrentMICR();
	void SetConcurrentMICR(BOOL bNewValue);
	long GetCropAreaCount();
	long GetDocumentHeight();
	void SetDocumentHeight(long nNewValue);
	long GetDocumentWidth();
	void SetDocumentWidth(long nNewValue);
	CString GetFileID();
	void SetFileID(LPCTSTR lpszNewValue);
	long GetFileIndex();
	void SetFileIndex(long nNewValue);
	CString GetImageData();
	long GetImageFormat();
	void SetImageFormat(long nNewValue);
	long GetImageMemoryStatus();
	CString GetImageTagData();
	void SetImageTagData(LPCTSTR lpszNewValue);
	long GetMapMode();
	void SetMapMode(long nNewValue);
	long GetMaxCropAreas();
	long GetQuality();
	void SetQuality(long nNewValue);
	CString GetQualityList();
	long GetRemainingImagesEstimate();
	long BeginInsertion(long Timeout);
	long BeginRemoval(long Timeout);
	long ClearImage(long By);
	long DefineCropArea(long CropAreaID, long X, long Y, long CX, long CY);
	long EndInsertion();
	long EndRemoval();
	long RetrieveImage(long CropAreaID);
	long RetrieveMemory(long By);
	long StoreImage(long CropAreaID);
	BOOL GetCapStatisticsReporting();
	BOOL GetCapUpdateStatistics();
	long ResetStatistics(LPCTSTR StatisticsBuffer);
	long RetrieveStatistics(BSTR* pStatisticsBuffer);
	long UpdateStatistics(LPCTSTR StatisticsBuffer);
	BOOL GetCapCompareFirmwareVersion();
	BOOL GetCapUpdateFirmware();
	long CompareFirmwareVersion(LPCTSTR FirmwareFileName, long* pResult);
	long UpdateFirmware(LPCTSTR FirmwareFileName);
	BOOL GetCapAutoContrast();
	BOOL GetCapContrast();
	long GetContrast();
	void SetContrast(long nNewValue);
	long ClearInputProperties();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COCSCN_H__207C7C25_2AC4_45E7_AE86_21DA0A0D9CBB__INCLUDED_)
