//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chkScan.rc
//
#define IDD_CHKSCAN_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_BTN_TIFREAD                 1000
#define IDC_BTN_READ                    1000
#define IDC_BTN_BMPREAD                 1001
#define IDC_BTN_MICRDATA                1002
#define IDC_BTN_MICRATTACH              1002
#define IDC_STC_RANGE                   1003
#define IDC_BTN_PRESCAN                 1004
#define IDC_BTN_COROP                   1005
#define IDC_BTN_IMAGEFIL                1005
#define IDC_BTN_STORE                   1005
#define IDC_BTN_CREATEF                 1007
#define IDC_BTN_ATTACH                  1008
#define IDC_BTN_READAREA2               1008
#define IDC_BTN_READMEMORY              1008
#define IDC_STC_IMBYTE                  1009
#define IDC_CHECKSCANNER1               1010
#define IDC_MICR1                       1012
#define IDC_STC_ERINFO                  1013
#define IDC_BTN_RETRIEVST               1013
#define IDC_STC_NORM                    1014
#define IDC_RADIO1                      1016
#define IDC_RDO_CROP1                   1016
#define IDC_RADIO2                      1017
#define IDC_RDO_CROP2                   1017
#define IDC_RADIO3                      1018
#define IDC_RDO_CROP3                   1018
#define IDC_STC_DS                      1019
#define IDC_STC_CA                      1020
#define IDC_CMB_STEP                    1025
#define IDC_STC_ESTI                    1026
#define IDC_STC_RESTESTI                1027
#define IDC_STC_CM                      1028
#define IDC_CMB_CM                      1029
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
