#if !defined(AFX_COMSR_H__63EEC191_C13D_4699_9D44_E1511C851228__INCLUDED_)
#define AFX_COMSR_H__63EEC191_C13D_4699_9D44_E1511C851228__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCoMsr wrapper class

class CCoMsr : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCoMsr)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xccb90122, 0xb81e, 0x11d2, { 0xab, 0x74, 0x0, 0x40, 0x5, 0x4c, 0x37, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetOpenResult();
	CString GetCheckHealthText();
	BOOL GetClaimed();
	BOOL GetDataEventEnabled();
	void SetDataEventEnabled(BOOL bNewValue);
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL bNewValue);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL bNewValue);
	long GetResultCode();
	long GetResultCodeExtended();
	long GetState();
	CString GetControlObjectDescription();
	long GetControlObjectVersion();
	CString GetServiceObjectDescription();
	long GetServiceObjectVersion();
	CString GetDeviceDescription();
	CString GetDeviceName();
	long CheckHealth(long Level);
	long ClaimDevice(long Timeout);
	long ClearInput();
	long Close();
	long DirectIO(long Command, long* pData, BSTR* pString);
	long Open(LPCTSTR DeviceName);
	long ReleaseDevice();
	CString GetAccountNumber();
	BOOL GetCapISO();
	BOOL GetCapJISOne();
	BOOL GetCapJISTwo();
	BOOL GetDecodeData();
	void SetDecodeData(BOOL bNewValue);
	CString GetExpirationDate();
	CString GetFirstName();
	CString GetMiddleInitial();
	BOOL GetParseDecodeData();
	void SetParseDecodeData(BOOL bNewValue);
	BOOL GetParseDecodedData();
	void SetParseDecodedData(BOOL bNewValue);
	CString GetServiceCode();
	CString GetSuffix();
	CString GetSurname();
	CString GetTitle();
	CString GetTrack1Data();
	CString GetTrack1DiscretionaryData();
	CString GetTrack2Data();
	CString GetTrack2DiscretionaryData();
	CString GetTrack3Data();
	long GetTracksToRead();
	void SetTracksToRead(long nNewValue);
	BOOL GetAutoDisable();
	void SetAutoDisable(BOOL bNewValue);
	long GetBinaryConversion();
	void SetBinaryConversion(long nNewValue);
	long GetDataCount();
	long GetErrorReportingType();
	void SetErrorReportingType(long nNewValue);
	long GetCapPowerReporting();
	long GetPowerNotify();
	void SetPowerNotify(long nNewValue);
	long GetPowerState();
	BOOL GetCapTransmitSentinels();
	CString GetTrack4Data();
	BOOL GetTransmitSentinels();
	void SetTransmitSentinels(BOOL bNewValue);
	BOOL GetCapStatisticsReporting();
	BOOL GetCapUpdateStatistics();
	long ResetStatistics(LPCTSTR StatisticsBuffer);
	long RetrieveStatistics(BSTR* pStatisticsBuffer);
	long UpdateStatistics(LPCTSTR StatisticsBuffer);
	BOOL GetCapCompareFirmwareVersion();
	BOOL GetCapUpdateFirmware();
	long CompareFirmwareVersion(LPCTSTR FirmwareFileName, long* pResult);
	long UpdateFirmware(LPCTSTR FirmwareFileName);
	long ClearInputProperties();
	long GetCapWritableTracks();
	long GetEncodingMaxLength();
	long GetTracksToWrite();
	void SetTracksToWrite(long nNewValue);
	long WriteTracks(const VARIANT& Data, long Timeout);
	CString GetAdditionalSecurityInformation();
	CString GetCapCardAuthentication();
	long GetCapDataEncryption();
	long GetCapDeviceAuthentication();
	BOOL GetCapTrackDataMasking();
	CString GetCardAuthenticationData();
	long GetCardAuthenticationDataLength();
	CString GetCardPropertyList();
	CString GetCardType();
	CString GetCardTypeList();
	long GetDataEncryptionAlgorithm();
	void SetDataEncryptionAlgorithm(long nNewValue);
	BOOL GetDeviceAuthenticated();
	long GetDeviceAuthenticationProtocol();
	CString GetTrack1EncryptedData();
	long GetTrack1EncryptedDataLength();
	CString GetTrack2EncryptedData();
	long GetTrack2EncryptedDataLength();
	CString GetTrack3EncryptedData();
	long GetTrack3EncryptedDataLength();
	CString GetTrack4EncryptedData();
	long GetTrack4EncryptedDataLength();
	CString GetWriteCardType();
	void SetWriteCardType(LPCTSTR lpszNewValue);
	long AuthenticateDevice(LPCTSTR Response);
	long DeauthenticateDevice(LPCTSTR Response);
	long RetrieveCardProperty(LPCTSTR Name, BSTR* pValue);
	long RetrieveDeviceAuthenticationData(BSTR* pChallenge);
	long UpdateKey(LPCTSTR Key, LPCTSTR KeyName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COMSR_H__63EEC191_C13D_4699_9D44_E1511C851228__INCLUDED_)
