//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MSR.rc
//
#define IDD_MSR_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_EDIT_ACCOUNT                1000
#define IDC_EDIT_DATE                   1001
#define IDC_EDIT_FIRST                  1002
#define IDC_EDIT_SUR                    1003
#define IDC_EDIT_MIDDLE                 1004
#define IDC_EDIT_TRACK1                 1005
#define IDC_EDIT_TRACK2                 1006
#define IDC_EDIT_TRACK3                 1007
#define IDC_EDIT_TRACK4                 1008
#define IDC_MSR1                        1009
#define IDC_LBL_TITLE                   1010
#define IDC_LBL_ACCOUNT                 1011
#define IDC_LBL_DATE                    1012
#define IDC_LBL_FIRST                   1013
#define IDC_LBL_SUR                     1014
#define IDC_LBL_MIDDLE                  1015
#define IDC_LBL_TRACK1                  1016
#define IDC_LBL_TRACK2                  1017
#define IDC_LBL_TRACK3                  1018
#define IDC_LBL_TRACK4                  1019
#define IDC_BTN_RETRIEVST               1020
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
