#if !defined(AFX_COTOT_H__E8B287DA_8367_4EA7_9F51_80B3CDEA328C__INCLUDED_)
#define AFX_COTOT_H__E8B287DA_8367_4EA7_9F51_80B3CDEA328C__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCoTot wrapper class

class CCoTot : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCoTot)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xccb90082, 0xb81e, 0x11d2, { 0xab, 0x74, 0x0, 0x40, 0x5, 0x4c, 0x37, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetOpenResult();
	CString GetCheckHealthText();
	BOOL GetClaimed();
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL bNewValue);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL bNewValue);
	long GetResultCode();
	long GetResultCodeExtended();
	long GetState();
	CString GetControlObjectDescription();
	long GetControlObjectVersion();
	CString GetServiceObjectDescription();
	long GetServiceObjectVersion();
	CString GetDeviceDescription();
	CString GetDeviceName();
	long CheckHealth(long Level);
	long ClaimDevice(long Timeout);
	long Close();
	long DirectIO(long Command, long* pData, BSTR* pString);
	long Open(LPCTSTR DeviceName);
	long ReleaseDevice();
	BOOL GetCapErrorDetection();
	BOOL GetCapSingleFile();
	BOOL GetCapTransactions();
	long GetFreeData();
	long GetNumberOfFiles();
	long GetTotalsSize();
	BOOL GetTransactionInProgress();
	long BeginTrans();
	long ClaimFile(long HTotalsFile, long Timeout);
	long CommitTrans();
	long Create(LPCTSTR FileName, long* pHTotalsFile, long Size, BOOL ErrorDetection);
	long Delete(LPCTSTR FileName);
	long Find(LPCTSTR FileName, long* pHTotalsFile, long* pSize);
	long FindByIndex(long Index, BSTR* pFileName);
	long Read(long HTotalsFile, BSTR* pData, long Offset, long Count);
	long RecalculateValidationData(long HTotalsFile);
	long ReleaseFile(long HTotalsFile);
	long Rename(long HTotalsFile, LPCTSTR FileName);
	long Rollback();
	long SetAll(long HTotalsFile, long Value);
	long ValidateData(long HTotalsFile);
	long Write(long HTotalsFile, LPCTSTR Data, long Offset, long Count);
	long GetBinaryConversion();
	void SetBinaryConversion(long nNewValue);
	long GetCapPowerReporting();
	long GetPowerNotify();
	void SetPowerNotify(long nNewValue);
	long GetPowerState();
	BOOL GetCapStatisticsReporting();
	BOOL GetCapUpdateStatistics();
	long ResetStatistics(LPCTSTR StatisticsBuffer);
	long RetrieveStatistics(BSTR* pStatisticsBuffer);
	long UpdateStatistics(LPCTSTR StatisticsBuffer);
	BOOL GetCapCompareFirmwareVersion();
	BOOL GetCapUpdateFirmware();
	long CompareFirmwareVersion(LPCTSTR FirmwareFileName, long* pResult);
	long UpdateFirmware(LPCTSTR FirmwareFileName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COTOT_H__E8B287DA_8367_4EA7_9F51_80B3CDEA328C__INCLUDED_)
