//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HTotals.rc
//
#define IDD_HTOTALS_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_BTN_CREATE                  1000
#define IDC_BTN_CHANGE                  1001
#define IDC_BTN_DELETE                  1002
#define IDC_BTN_REGISTER                1003
#define IDC_EDIT_CREATE                 1004
#define IDC_EDIT_CHANGE                 1005
#define IDC_EDIT_REGISTER               1006
#define IDC_LIST_FILE                   1007
#define IDC_TOTALS1                     1008
#define IDC_STC_FILELIST                1009
#define IDC_BTN_RETRIEVST               1013
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
