//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Display.rc
//
#define IDD_DISPLAY_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_BTN_CLEAR                   1000
#define IDC_BTN_POSITION                1001
#define IDC_BTN_BLINK                   1002
#define IDC_BTN_TELETYPE                1003
#define IDC_BTN_CONTROL                 1004
#define IDC_BTN_SCLEFT                  1005
#define IDC_BTN_SCRIGHT                 1006
#define IDC_BTN_ORNAMENTS               1007
#define IDC_BTN_BITMAP                  1008
#define IDC_LINEDISPLAY1                1009
#define IDC_BTN_DEFINEGLYPH             1010
#define IDC_BTN_READCHARACTER           1013
#define IDC_EDIT1                       1014
#define IDC_STC_SCROLL                  1016
#define IDC_STC_GDISP                   1017
#define IDC_BTN_RETRIEVST               1020
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
