//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MICR.rc
//
#define IDD_MICR_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_EDIT_RAWDATA                1000
#define IDC_EDIT_ACCOUNT                1001
#define IDC_EDIT_AMOUNT                 1002
#define IDC_EDIT_BANK                   1003
#define IDC_EDIT_CHECK                  1004
#define IDC_EDIT_COUNTRY                1005
#define IDC_EDIT_EPC                    1006
#define IDC_EDIT_SERIAL                 1007
#define IDC_EDIT_TRANSIT                1008
#define IDC_BTN_INSERT                  1009
#define IDC_BTN_PRINT                   1010
#define IDC_BTN_REMOVE                  1011
#define IDC_BTN_RETRIEVST               1013
#define IDC_MICR1                       1022
#define IDC_POSPRINTER1                 1023
#define IDC_STC_RD                      1024
#define IDC_STC_AN                      1025
#define IDC_STC_AMOUNT                  1026
#define IDC_STC_BN                      1027
#define IDC_STC_CT                      1028
#define IDC_STC_CC                      1029
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031
#define IDC_STC_EPC                     1033
#define IDC_STC_SN                      1034
#define IDC_STC_TN                      1035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
