//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Keylock.rc
//
#define IDD_KEYLOCK_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_EDIT_POSITION               1000
#define IDC_BTN_KEYPOSI                 1001
#define IDC_KEYLOCK1                    1002
#define IDC_STC_CHGLOCK                 1003
#define IDC_STC_KEYPOS                  1004
#define IDC_BTN_RETRIEVST               1013
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
