//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Drawer.rc
//
#define IDD_DRAWER_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_XMLVIEW_DIALOG              131
#define IDC_BTN_OPEN                    1000
#define IDC_LBL_STATUS                  1001
#define IDC_LBL_POWER                   1002
#define IDC_CASHDRAWER1                 1003
#define IDC_LBL_TSTATIC                 1004
#define IDC_LBL_TPOWER                  1005
#define IDC_BTN_RETRIEVST               1020
#define IDC_EDIT_RETRIEVST              1030
#define IDC_EXPLORER_WMLVIEW            1031
#define IDC_STC_DST                     1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
