#if !defined(AFX_OPOSELECTRONICJOURNAL_H__3C85E907_4662_46BE_8BB1_BD7DF4981EEC__INCLUDED_)
#define AFX_OPOSELECTRONICJOURNAL_H__3C85E907_4662_46BE_8BB1_BD7DF4981EEC__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COPOSElectronicJournal wrapper class

class COPOSElectronicJournal : public CWnd
{
protected:
	DECLARE_DYNCREATE(COPOSElectronicJournal)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xccb90272, 0xb81e, 0x11d2, { 0xab, 0x74, 0x0, 0x40, 0x5, 0x4c, 0x37, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetOpenResult();
	BOOL GetAutoDisable();
	void SetAutoDisable(BOOL bNewValue);
	long GetBinaryConversion();
	void SetBinaryConversion(long nNewValue);
	long GetCapPowerReporting();
	CString GetCheckHealthText();
	BOOL GetClaimed();
	long GetDataCount();
	BOOL GetDataEventEnabled();
	void SetDataEventEnabled(BOOL bNewValue);
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL bNewValue);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL bNewValue);
	long GetOutputID();
	long GetPowerNotify();
	void SetPowerNotify(long nNewValue);
	long GetPowerState();
	long GetResultCode();
	long GetResultCodeExtended();
	long GetState();
	CString GetControlObjectDescription();
	long GetControlObjectVersion();
	CString GetServiceObjectDescription();
	long GetServiceObjectVersion();
	CString GetDeviceDescription();
	CString GetDeviceName();
	BOOL GetCapStatisticsReporting();
	BOOL GetCapUpdateStatistics();
	BOOL GetCapCompareFirmwareVersion();
	BOOL GetCapUpdateFirmware();
	long CheckHealth(long Level);
	long ClaimDevice(long Timeout);
	long ClearInput();
	long ClearOutput();
	long Close();
	long DirectIO(long Command, long* pData, BSTR* pString);
	long Open(LPCTSTR DeviceName);
	long ReleaseDevice();
	long ResetStatistics(LPCTSTR StatisticsBuffer);
	long RetrieveStatistics(BSTR* pStatisticsBuffer);
	long UpdateStatistics(LPCTSTR StatisticsBuffer);
	long CompareFirmwareVersion(LPCTSTR FirmwareFileName, long* pResult);
	long UpdateFirmware(LPCTSTR FirmwareFileName);
	BOOL GetAsyncMode();
	void SetAsyncMode(BOOL bNewValue);
	BOOL GetCapAddMarker();
	BOOL GetCapErasableMedium();
	BOOL GetCapInitializeMedium();
	BOOL GetCapMediumIsAvailable();
	BOOL GetCapPrintContent();
	BOOL GetCapPrintContentFile();
	BOOL GetCapRetrieveCurrentMarker();
	BOOL GetCapRetrieveMarker();
	BOOL GetCapRetrieveMarkerByDateTime();
	BOOL GetCapRetrieveMarkersDateTime();
	long GetCapStation();
	BOOL GetCapStorageEnabled();
	BOOL GetCapSuspendPrintContent();
	BOOL GetCapSuspendQueryContent();
	BOOL GetCapWaterMark();
	BOOL GetFlagWhenIdle();
	void SetFlagWhenIdle(BOOL bNewValue);
	CY GetMediumFreeSpace();
	CString GetMediumID();
	BOOL GetMediumIsAvailable();
	CY GetMediumSize();
	long GetStation();
	void SetStation(long nNewValue);
	BOOL GetStorageEnabled();
	void SetStorageEnabled(BOOL bNewValue);
	BOOL GetSuspended();
	BOOL GetWaterMark();
	void SetWaterMark(BOOL bNewValue);
	long AddMarker(LPCTSTR Marker);
	long CancelPrintContent();
	long CancelQueryContent();
	long EraseMedium();
	long InitializeMedium(LPCTSTR MediumID);
	long PrintContent(LPCTSTR FromMarker, LPCTSTR ToMarker);
	long PrintContentFile(LPCTSTR FileName);
	long QueryContent(LPCTSTR FileName, LPCTSTR FromMarker, LPCTSTR ToMarker);
	long ResumePrintContent();
	long ResumeQueryContent();
	long RetrieveCurrentMarker(long MarkerType, BSTR* pMarker);
	long RetrieveMarker(long MarkerType, long SessionNumber, long DocumentNumber, BSTR* pMarker);
	long RetrieveMarkerByDateTime(long MarkerType, LPCTSTR DateTime, LPCTSTR MarkerNumber, BSTR* pMarker);
	long RetrieveMarkersDateTime(LPCTSTR Marker, BSTR* pDateTime);
	long SuspendPrintContent();
	long SuspendQueryContent();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OPOSELECTRONICJOURNAL_H__3C85E907_4662_46BE_8BB1_BD7DF4981EEC__INCLUDED_)
